### PR TITLE
Fix FTBFS

### PR DESCRIPTION
**Pull request by rzr**

### CODE REVIEW

**Comment by bneijt** [comment]
Thank you for your pull request! Could you point me to the FTBFS report? It seems like it builds on my system and seems to run fine without the pointer patch you send in.

**Comment by rzr** [comment]
Sure :  g++ (Debian 4.9.2-10) 4.9.2

g++ -DPACKAGE_NAME=\"metalink\" -DPACKAGE_TARNAME=\"metalink\" -DPACKAGE_VERSION=\"0.3.6\" -DPACKAGE_STRING=\"metalink\ 0.3.6\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"metalin$
In file included from /usr/include/c++/4.9/vector:64:0,
                 from src/Hash/HashPieces/HashPieces.hh:35,
                 from src/Hash/HashPieces/HashPieces.ih:20,
                 from src/Hash/HashPieces/xml.cc:23:
/usr/include/c++/4.9/bits/stl_vector.h: In instantiation of ‘class std::vectorbneijt::Hash’:
src/Hash/HashPieces/xml.cc:31:20:   required from here
/usr/include/c++/4.9/bits/stl_vector.h:713:7: error: invalid abstract parameter type ‘bneijt::Hash’
       resize(size_type __new_size, value_type __x = value_type())
       ^
In file included from src/Hash/HashPieces/HashPieces.hh:38:0,
                 from src/Hash/HashPieces/HashPieces.ih:20,
                 from src/Hash/HashPieces/xml.cc:23:
src/Hash/HashPieces/../Hash.hh:31:7: note:   because the following virtual functions are pure within ‘bneijt::Hash’:
 class Hash
       ^
src/Hash/HashPieces/../Hash.hh:34:23: note:     virtual std::string bneijt::Hash::name() const
   virtual std::string name() const = 0;
                       ^
src/Hash/HashPieces/../Hash.hh:35:16: note:     virtual void bneijt::Hash::update(const char_, unsigned int)
   virtual void update(char const *bytes, unsigned numbytes) = 0;
                ^
src/Hash/HashPieces/../Hash.hh:36:16: note:     virtual void bneijt::Hash::finalize()
   virtual void finalize() = 0;
                ^
src/Hash/HashPieces/../Hash.hh:37:30: note:     virtual const string& bneijt::Hash::value() const
   virtual std::string const &value() const = 0;
                              ^
Makefile:903: recipe for target 'src/Hash/HashPieces/metalink-xml.o' failed
make: *_\* [src/Hash/HashPieces/metalink-xml.o] Error 1

If you make a new release soon, please let me do additional build test to make sure it will build on most configurations , If project is still living I could help maintain it debian's side too.

**Comment by bneijt** [comment]
I'm going to move the build to CMake, add Travis-CI support. I think it may be a g++ version problem, which I hope to clear up with the travis builds.

**Comment by bneijt** [comment]
I've dropped support for autotools and put CMake in place with a Travis-CI configuration. It builds on g++-4.8 on travis-ci and 5.2.0 on my local machine.

Could you try the new build with your debian installation? It may have been a missing "-std=c++11" that caused the build failure.

**Comment by rzr** [comment]
I confirm it builds fine with this C++11 flag, 

So I removed this change on vector<Hash*>  
( 9def72fc3e70cc4ec467b30db6fa5afb04dce3db )
from my master branch.

but I still think it is valid ( see declaration of std::vector<Hash *> d_pieces;  )

And replaced with install feature

**Comment by rzr** [comment]
Hi,
Is this project still maintained or active ?

**Comment by antbryan** [comment]
@rzr what are you trying to do? another project may serve you better.

**Comment by bneijt** [comment]
The only diff left here is some changes in the `.gitignore` and changes to the `CMakefile`. For me cmake discoveres the binaries automatically already and package build seems to go fine with this setting.

@rzr please consider opening a new issue describing the fixes these changes make and add the pull request there.

**Pull request closed without merging**
